name: iafinalprojectfront
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.4.1
  get_it: ^8.0.0
  go_router: ^13.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  gap: ^3.0.1
  introduction_screen: ^3.1.14
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.14.0
  animate_do: ^3.3.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/numbers/
    - assets/translations/